import Link from "next/link";

import demoProject from "@/demo/project.json";
import { currentStep, finishedForCurrentStep } from "@/core/flow";
import type { Project } from "@/core/types";
import { BriefPanel } from "@/features/brief/BriefPanel";
import { ReadOnly } from "@/features/demo/ReadOnly";
import { NodesPanel } from "@/features/nodes/NodesPanel";
import { TodoList } from "@/features/opportunities/TodoList";
import { PlanPanel } from "@/features/plan/PlanPanel";
import { StepRail } from "@/features/plan/StepRail";
import { ScanPanel } from "@/features/scan/ScanPanel";
import { StepFocus } from "@/features/workspace/StepFocus";

const project = demoProject as unknown as Project;

export const metadata = {
  title: "Playbook - a real run",
  description: "A goal taken all the way through: researched, planned, scouted, and underway.",
};

/**
 * A finished run, frozen.
 *
 * Everything here was generated by the live pipeline against a real goal. It is
 * saved rather than regenerated so it loads instantly and cannot be changed by
 * whoever looks at it next. Same components as the real app; the controls just
 * do not fire.
 */
export default function DemoPage() {
  const step = currentStep(project);
  const done = finishedForCurrentStep(project).length;

  return (
    <ReadOnly>
      <div className="mx-auto flex w-full max-w-6xl flex-col gap-8 px-6 py-8 lg:flex-row lg:gap-12 lg:py-12">
        <aside className="flex shrink-0 flex-col gap-8 lg:sticky lg:top-12 lg:h-fit lg:w-60">
          <Link
            href="/welcome"
            className="text-muted-foreground hover:text-foreground text-sm underline-offset-4 hover:underline"
          >
            &larr; Playbook
          </Link>

          <div className="flex flex-col gap-1">
            <p className="text-muted-foreground font-mono text-[11px] tracking-[0.14em] uppercase">
              Goal
            </p>
            <p className="text-sm leading-snug font-medium text-balance">{project.title}</p>
          </div>

          <StepRail project={project} />

          <Link
            href="/login"
            className="border-foreground bg-foreground text-background rounded-lg border px-4 py-2.5 text-center text-sm font-medium"
          >
            Run your own goal
          </Link>
        </aside>

        <main className="flex min-w-0 flex-1 flex-col gap-8">
          <div className="border-border bg-card rounded-xl border p-4">
            <p className="text-sm leading-relaxed">
              <span className="font-medium">This is a saved run.</span>{" "}
              <span className="text-muted-foreground">
                Every word below was generated live, including the research and the opportunities,
                which are real programs with real deadlines. It is frozen so it loads instantly and
                stays the same for the next person, so the buttons here are inert.
              </span>
            </p>
          </div>

          <StepFocus project={project} />
          <TodoList project={project} />

          <div className="border-border flex flex-col gap-6 border-t pt-8">
            <div className="flex flex-col gap-1.5">
              <h2 className="text-lg font-semibold tracking-tight">How it got here</h2>
              <p className="text-muted-foreground text-sm">
                {step
                  ? `${done} finished on this step. Once something is done, the system judges whether the completion signals are met before anything advances.`
                  : "The stages behind this run."}
              </p>
            </div>

            <BriefPanel project={project} />
            <PlanPanel project={project} />
            <NodesPanel project={project} />
            <ScanPanel project={project} />
          </div>
        </main>
      </div>
    </ReadOnly>
  );
}
